### ISSUE TITLE
Definisi Current Streak 

### ISSUE THREAD

**Issue by hendrasan** [pveyes/katla#14]
Kalau melihat logic di code, currentStreak adalah increment setiap kali tebakan benar, tapi kalau mengacu ke Wordle, sepertinya ada pengecekan tambahan ke hari.

Kalau gak salah, gua pernah udah streak 3 hari misalnya, terus skip 1 hari, terus pas selanjutnya tebakan gua benar, streaknya balik ke 1 lagi.

**Comment by pveyes** [comment]
Menarik, implementasi yang sekarang cuma ngeliat sekilas game state yang disimpan sama wordle. Kalo harus streak per hari kayaknya perlu save 1 state lagi terakhir menang kapan.

Tp kayaknya valid sih, user harus main tiap hari buat keep streaknya 👍
