### ISSUE TITLE
Better flip animation

### ISSUE THREAD

**Issue by adwindito** [pveyes/katla#23]
**Problem**: Current flip animation for every tile feels so fast

**Solution**:
- Adding new css class in global.css named .flipInOut
![flipinout](https://user-images.githubusercontent.com/28857285/150910985-01b042fc-4a13-4d98-9bd0-777763623f49.png)

- Change the animation to "flipInOut" and animation duration to "1000ms" in Tile.tsx

**Comment by pveyes** [comment]
Feel free to make PR if you want, if not I'll probably pick it up later

Thanks for the suggestion
