### ISSUE TITLE
Bikin versi bahasa daerah (misal Jawa, Sunda, Minang, dsb) juga dong?

### ISSUE THREAD

**Issue by hrasyid** [pveyes/katla#24]

**Comment by dotslashf** [comment]
Sepertinya akan susah sih, karena saat ini afaik tidak ada official api untuk bahasa daerah yang bisa bantu untuk mengoleksi kumpulan katanya

**Comment by pveyes** [comment]
untuk versi bahasa daerah sendiri tidak akan di support di sini, mungkin yang bisa dibantu adalah bagaimana orang lain bisa dengan mudah melakukan fork repo untuk mengubah database kata ke bahasa daerah masing2
