### ISSUE TITLE
Validation on user when inputing answer

### ISSUE THREAD

**Issue by dotslashf** [pveyes/katla#31]
Shall we add another validation for user when they inputing more than 5 characters? Similar to when user's input lower than 5 characters:

```js
const userAnswer = game.state.answers[game.state.attempt];
if (userAnswer.length < 5) {
  markInvalid();
  showMessage("Tidak cukup huruf");
  return;
}
```

**Comment by pveyes** [comment]
Seeing that wordle doesn't do anything either , I don't think we should
