### ISSUE TITLE
Easy access to answers

### ISSUE THREAD

**Issue by ElrondRafsaAdjani** [pveyes/katla#47]
Answers are easily found out in the .script folder that are opened to the public. This made it less fun for the user. Please hide the answers :D

**Comment by pveyes** [comment]
@ElrondRafsaAdjani it's only visible for people who are familiar with GitHub, and knowingly visit this repo just to look for the answer. Besides, this is already slightly better than wordle where you can see future answers.

Also there's an easier way to cheat, just use new/incognito browser and fill the same word 6 times to get the answer
