### ISSUE TITLE
Should use secret key or some kind of protection layer on hashing answer

### ISSUE THREAD

**Issue by utopictown** [pveyes/katla#8]
currently the result can just be decoded easily by fetching the hash result from /api/hash then run the decode function on other machine

**Comment by pveyes** [comment]
I think we can add another salt using env var to obfuscate it even more, but if they're that determined to cheat, there's an easier way (like changing the share text, or simply writing until they get the answer in an incognito window) 🤷‍♂️

for now I'd rather focus on having 1-1 feature parity with Wordle and fixing bugs

**Comment by pveyes** [comment]
After I think about it some more, I decided to not pursue this, as the effort outweigh the benefit
