### ISSUE TITLE
Should show the correct word when you failed

### ISSUE THREAD

**Issue by resir014** [pveyes/katla#9]
In the original Wordle, when you fail a puzzle the correct word will show up at the top of the blocks. When I failed my run, it didn't work.

Example (blurred since spoiler for today's Wordle):

![image](https://user-images.githubusercontent.com/5663877/150522569-a9ab7ce4-9b3c-4441-85c0-0fb0469f40b2.png)

**Comment by pveyes** [comment]
either it's a bug or the message is not shown long enough, but the logic to display the answer is already exist in https://github.com/pveyes/katla/blob/main/pages/index.tsx#L204

**Comment by pveyes** [comment]
closing this as per #18
